import assert from 'node:assert/strict';
import {execFileSync} from 'node:child_process';
import {readFileSync,writeFileSync} from 'node:fs';
import {join} from 'node:path';
import {fileURLToPath} from 'node:url';
const root=process.argv[2];
assert.ok(root?.startsWith('/tmp/workshop-visuals-native-'));
const helper=fileURLToPath(new URL('./native_visual_mcp.mjs',import.meta.url));
const evidence=JSON.parse(readFileSync(join(root,'acceptance/analysis.swarm_trajectories.v1.recorded_run_binding.json')));
const {visualId,revision}=evidence;
const call=(operation,fields={})=>JSON.parse(execFileSync(process.execPath,[helper,root,visualId,operation,JSON.stringify({revision,...fields})],{encoding:'utf8',timeout:50000}));
call('manage:show',{presentation:'pane'});
const initial=call('inspect').state;
const corpus=initial.values['recorded.source'];assert.ok(corpus.count>0,'A populated persisted read model is required');
const query={schemaVersion:'synth.visuals-core.v1',where:{op:'all'}};
const page=call('corpus.query',{corpus,query,window:{offset:0,limit:1}});
assert.equal(page.total,corpus.count);assert.equal(page.rows.length,1);
assert.ok(!('details' in page.rows[0])&&!('events' in page.rows[0]));
const row=page.rows[0];
const details=call('corpus.detail',{corpus,rowId:row.id});assert.ok(details.details);
const recording=call('record.start');
let state=call('act',{action:{id:crypto.randomUUID(),kind:'presentation.patch',expectedStateVersion:initial.stateVersion,payload:{values:{'recorded.filters':{kind:row.kind},'recorded.history':[{}],'recorded.selected':row.id}}}}).state;
const selected=call('capture.pixels');
assert.equal(selected.pixelCut.paint.verified,true);
call('record.stop');
state=call('record.seek',{recordingId:recording.recordingId,sequence:0,expectedStateVersion:call('inspect').state.stateVersion}).state;
assert.deepEqual(state.values,initial.values);
state=call('restore',{checkpointId:selected.pixelCut.checkpoint.id,expectedStateVersion:state.stateVersion}).state;
assert.equal(state.values['recorded.selected'],row.id);
assert.deepEqual(state.values['recorded.history'],[{}]);
assert.deepEqual(call('corpus.detail',{corpus,rowId:row.id}),details);
const restored=call('capture.pixels');assert.equal(restored.pixelCut.paint.verified,true);
const result={visualId,revision,corpus,selectedId:row.id,recordingId:recording.recordingId,metadataOnly:true,lazyDetail:true,restoredNavigation:true,selected,restored};
writeFileSync(join(root,'acceptance/recorded-collection-roundtrip.json'),JSON.stringify(result,null,2));
console.log(JSON.stringify({visualId,revision,count:corpus.count,recordingId:recording.recordingId,selected:selected.path,restored:restored.path}));
