//! tauri-specta boundary scaffold (Wave 2 stretch).
//!
//! # Dual-path registration (do not break invoke)
//!
//! `crate::run()` still registers **all** commands via `tauri::generate_handler!`.
//! That keeps the existing renderer `invokeCommand(COMMANDS.*, …)` path working
//! for ~120 commands.
//!
//! This module owns a growing `tauri_specta::Builder` used **only** for:
//! 1. TypeScript binding export → `src/renderer/src/generated/protocol.ts`
//! 2. Documenting the eventual cutover sketch (below)
//!
//! The seed command lives here (not in `lib.rs`) so `#[tauri::command]` +
//! `pub` do not collide with macro reimports at the crate root.
//!
//! # Cutover sketch (when every command is collected)
//!
//! ```ignore
//! let specta = contract::specta::builder();
//! // #[cfg(debug_assertions)] { specta.export(...) }
//! tauri::Builder::default()
//!     .invoke_handler(specta.invoke_handler())  // replaces generate_handler!
//!     .setup(move |app| { specta.mount_events(app); Ok(()) })
//! ```
//!
//! Until then: never call `builder().invoke_handler()` from `run()` — it would
//! drop every command not listed in `collect_commands!`.
//!
//! # Migrating the next command
//!
//! 1. `#[derive(specta::Type)]` on arg/result DTOs (and `AppError` when ready).
//! 2. Add `#[specta::specta]` next to `#[tauri::command]` (keep commands in a
//!    submodule — not `lib.rs` root if `pub`).
//! 3. Append the fn to `collect_commands!` in [`builder`].
//! 4. Re-run `cargo test -p synth-desktop export_specta_protocol_bindings -- --nocapture`
//!    (or debug-assert export in [`export_typescript_bindings`]).
//! 5. Prefer generated types from `generated/protocol.ts` at the bridge edge.

use crate::instance::{self, InstanceDiagnostics};
use specta_typescript::Typescript;
use tauri_specta::{collect_commands, Builder};

/// Absolute-ish path from `src-tauri/` to the committed renderer binding file.
pub const PROTOCOL_TS_RELATIVE: &str = "../src/renderer/src/generated/protocol.ts";

/// Seed command for tauri-specta codegen. Still listed in `generate_handler!`
/// so `invokeCommand(COMMANDS.DESKTOP_INSTANCE_DIAGNOSTICS)` keeps working.
#[tauri::command]
#[specta::specta]
pub fn desktop_instance_diagnostics() -> InstanceDiagnostics {
    instance::diagnostics()
}

/// Specta builder for the subset of commands ready for codegen.
pub fn builder() -> Builder<tauri::Wry> {
    Builder::<tauri::Wry>::new().commands(collect_commands![desktop_instance_diagnostics])
}

/// Write TypeScript bindings for the collected subset.
///
/// Safe to call from tests and from `run()` under `debug_assertions`. Does not
/// touch invoke registration.
pub fn export_typescript_bindings() -> Result<(), String> {
    // CARGO_MANIFEST_DIR is src-tauri/; PROTOCOL_TS_RELATIVE is relative to that.
    let path = std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join(PROTOCOL_TS_RELATIVE);
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent).map_err(|error| error.to_string())?;
    }
    builder()
        .export(
            Typescript::default().header("// @generated by tauri-specta — do not edit by hand.\n"),
            &path,
        )
        .map_err(|error| error.to_string())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn export_specta_protocol_bindings() {
        export_typescript_bindings().expect("export specta TypeScript bindings");
        let path = std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join(PROTOCOL_TS_RELATIVE);
        let body = std::fs::read_to_string(&path).expect("read generated protocol.ts");
        assert!(
            body.contains("desktop_instance_diagnostics")
                || body.contains("desktopInstanceDiagnostics"),
            "generated bindings should mention the seed command; got {} bytes",
            body.len()
        );
        assert!(
            body.contains("InstanceDiagnostics"),
            "generated bindings should include InstanceDiagnostics"
        );
    }
}
