use super::Database;
use anyhow::Result;
use chrono::Utc;
use rusqlite::{params, Connection};
use serde::{Deserialize, Serialize};
use serde_json::Value;
use std::{collections::{BTreeMap, HashMap}, sync::Arc};
use tokio::sync::Mutex;

#[derive(Clone, Copy, Debug, Deserialize, Serialize, PartialEq, Eq, PartialOrd, Ord)]
#[serde(rename_all = "snake_case")]
pub enum MeasurementKind { Decode, ObservedStream, EndToEnd, ProviderReported }
impl MeasurementKind {
    fn as_str(self)->&'static str { match self { Self::Decode=>"decode",Self::ObservedStream=>"observed_stream",Self::EndToEnd=>"end_to_end",Self::ProviderReported=>"provider_reported" } }
    fn parse(value:&str)->Self { match value {"decode"=>Self::Decode,"end_to_end"=>Self::EndToEnd,"provider_reported"=>Self::ProviderReported,_=>Self::ObservedStream} }
}

#[derive(Clone, Debug)]
pub struct ModelPerformanceSample {
    pub id:String,pub provider:String,pub model_id:String,pub session_id:Option<String>,pub run_id:Option<String>,pub request_id:String,
    pub measurement_kind:MeasurementKind,pub status:String,pub started_at_ms:i64,pub first_output_at_ms:Option<i64>,pub last_output_at_ms:Option<i64>,pub completed_at_ms:i64,
    pub input_tokens:Option<i64>,pub cached_input_tokens:Option<i64>,pub reasoning_tokens:Option<i64>,pub output_tokens:Option<i64>,pub ttft_ms:Option<f64>,pub observed_output_tps:Option<f64>,pub end_to_end_output_tps:Option<f64>,
}
#[derive(Clone, Debug, Serialize, PartialEq)]
#[serde(rename_all="camelCase")]
pub struct ModelPerformanceSummary { pub provider:String,pub model_id:String,pub measurement_kind:MeasurementKind,pub sample_count:usize,pub tps_p50:Option<f64>,pub tps_p95:Option<f64>,pub ttft_p50_ms:Option<f64>,pub last_observed_at:String }

#[derive(Clone)] pub struct ModelPerformanceRepository{db:Arc<Database>}
impl ModelPerformanceRepository{pub fn new(db:Arc<Database>)->Self{Self{db}}pub async fn record(&self,sample:ModelPerformanceSample)->Result<()>{self.db.run(move|conn|record(conn,sample)).await}pub async fn summaries(&self)->Result<Vec<ModelPerformanceSummary>>{self.db.run(summaries).await}}

#[derive(Default)] struct Usage{input:Option<i64>,cached:Option<i64>,reasoning:Option<i64>,output:Option<i64>}
struct Active{provider:String,model:String,request:String,started:i64,first:Option<i64>,last:Option<i64>,usage:Usage}
pub struct ModelPerformanceTracker{repository:ModelPerformanceRepository,active:Mutex<HashMap<String,Active>>}
impl ModelPerformanceTracker{
 pub fn new(db:Arc<Database>)->Self{Self{repository:ModelPerformanceRepository::new(db),active:Mutex::new(HashMap::new())}}
 pub async fn start(&self,session:&str,provider:String,model:String,request:String){self.active.lock().await.insert(session.into(),Active{provider,model,request,started:Utc::now().timestamp_millis(),first:None,last:None,usage:Usage::default()});}
 pub async fn identify(&self,session:&str,pending:&str,request:String){if let Some(active)=self.active.lock().await.get_mut(session){if active.request==pending{active.request=request}}}
 pub async fn discard(&self,session:&str,pending:&str){let mut turns=self.active.lock().await;if turns.get(session).is_some_and(|turn|turn.request==pending){turns.remove(session);}}
 pub async fn observe(&self,session:&str,method:&str,params:&Value){let now=Utc::now().timestamp_millis();let terminal=matches!(method,"turn/completed"|"turn/failed"|"turn/interrupted");{let mut turns=self.active.lock().await;let Some(turn)=turns.get_mut(session)else{return};if output_delta(method,params){turn.first.get_or_insert(now);turn.last=Some(now)}if method.to_ascii_lowercase().contains("usage")||terminal{if let Some(usage)=extract_usage(params){turn.usage=usage}}}if terminal{let status=if method=="turn/completed"{"completed"}else if method=="turn/failed"{"failed"}else{"interrupted"};self.finish(session,status,Some(now)).await}}
 pub async fn interrupt(&self,session:&str){self.finish(session,"interrupted",None).await}
 async fn finish(&self,session:&str,status:&str,completed:Option<i64>){let Some(turn)=self.active.lock().await.remove(session)else{return};let completed=completed.unwrap_or_else(||Utc::now().timestamp_millis());let output=turn.usage.output.filter(|v|*v>0);let stream=turn.first.zip(turn.last).map(|(a,b)|(b-a)as f64/1000.).filter(|v|*v>0.);let e2e=((completed-turn.started)as f64/1000.).max(0.);let observed=output.zip(stream).map(|(n,s)|n as f64/s);let end=output.filter(|_|e2e>0.).map(|n|n as f64/e2e);let request=turn.request;let sample=ModelPerformanceSample{id:format!("perf:{}:{}",turn.provider,request),provider:turn.provider,model_id:turn.model,session_id:Some(session.into()),run_id:Some(request.clone()),request_id:request,measurement_kind:if observed.is_some(){MeasurementKind::ObservedStream}else{MeasurementKind::EndToEnd},status:status.into(),started_at_ms:turn.started,first_output_at_ms:turn.first,last_output_at_ms:turn.last,completed_at_ms:completed,input_tokens:turn.usage.input,cached_input_tokens:turn.usage.cached,reasoning_tokens:turn.usage.reasoning,output_tokens:output,ttft_ms:turn.first.map(|v|(v-turn.started).max(0)as f64),observed_output_tps:observed,end_to_end_output_tps:end};if let Err(error)=self.repository.record(sample).await{eprintln!("model performance sample could not be persisted: {error:#}")}}
}
fn integer(v:&Value,names:&[&str])->Option<i64>{names.iter().find_map(|k|v.get(*k).and_then(Value::as_i64)).filter(|v|*v>=0)}
fn usage(v:&Value)->Option<Usage>{let output=integer(v,&["output_tokens","outputTokens","completion_tokens","completionTokens"])?;let details=v.get("output_tokens_details").or_else(||v.get("outputTokensDetails"));Some(Usage{input:integer(v,&["input_tokens","inputTokens","prompt_tokens","promptTokens"]),cached:integer(v,&["cached_input_tokens","cachedInputTokens","cached_tokens","cachedTokens"]),reasoning:details.and_then(|d|integer(d,&["reasoning_tokens","reasoningTokens"])).or_else(||integer(v,&["reasoning_tokens","reasoningTokens","reasoning_output_tokens","reasoningOutputTokens"])),output:Some(output)})}
fn extract_usage(v:&Value)->Option<Usage>{["/lastUsage","/lastTokenUsage","/tokenUsage/last","/tokenUsage/lastUsage","/tokenUsage/lastTokenUsage","/turn/lastUsage","/turn/lastTokenUsage","/turn/tokenUsage/last","/turn/tokenUsage/lastUsage","/turn/usage","/usage"].iter().find_map(|p|v.pointer(p).and_then(usage))}
fn output_delta(method:&str,v:&Value)->bool{let m=method.to_ascii_lowercase();(m.contains("agentmessage/delta")||m.contains("agent_message/delta")||m.contains("outputtext/delta")||m.contains("output_text/delta"))&&v.get("delta").and_then(Value::as_str).is_some_and(|v|!v.is_empty())}
fn finite(v:Option<f64>)->Option<f64>{v.filter(|v|v.is_finite()&&*v>0.)}
fn valid_fk(conn:&Connection,table:&str,value:Option<String>)->Result<Option<String>>{let Some(value)=value else{return Ok(None)};let exists:bool=conn.query_row(&format!("SELECT EXISTS(SELECT 1 FROM {table} WHERE id=?1)"),params![&value],|row|row.get(0))?;Ok(exists.then_some(value))}
fn record(conn:&Connection,mut s:ModelPerformanceSample)->Result<()>{s.ttft_ms=finite(s.ttft_ms);s.observed_output_tps=finite(s.observed_output_tps);s.end_to_end_output_tps=finite(s.end_to_end_output_tps);s.session_id=valid_fk(conn,"sessions",s.session_id)?;s.run_id=valid_fk(conn,"runs",s.run_id)?;conn.execute("INSERT INTO model_performance_samples(id,provider,model_id,session_id,run_id,request_id,measurement_kind,status,started_at_ms,first_output_at_ms,last_output_at_ms,completed_at_ms,input_tokens,cached_input_tokens,reasoning_tokens,output_tokens,ttft_ms,observed_output_tps,end_to_end_output_tps,created_at)VALUES(?1,?2,?3,?4,?5,?6,?7,?8,?9,?10,?11,?12,?13,?14,?15,?16,?17,?18,?19,?20)ON CONFLICT(provider,request_id)DO UPDATE SET status=excluded.status,first_output_at_ms=COALESCE(excluded.first_output_at_ms,model_performance_samples.first_output_at_ms),last_output_at_ms=COALESCE(excluded.last_output_at_ms,model_performance_samples.last_output_at_ms),completed_at_ms=excluded.completed_at_ms,input_tokens=COALESCE(excluded.input_tokens,model_performance_samples.input_tokens),cached_input_tokens=COALESCE(excluded.cached_input_tokens,model_performance_samples.cached_input_tokens),reasoning_tokens=COALESCE(excluded.reasoning_tokens,model_performance_samples.reasoning_tokens),output_tokens=COALESCE(excluded.output_tokens,model_performance_samples.output_tokens),ttft_ms=COALESCE(excluded.ttft_ms,model_performance_samples.ttft_ms),observed_output_tps=COALESCE(excluded.observed_output_tps,model_performance_samples.observed_output_tps),end_to_end_output_tps=COALESCE(excluded.end_to_end_output_tps,model_performance_samples.end_to_end_output_tps)",params![s.id,s.provider,s.model_id,s.session_id,s.run_id,s.request_id,s.measurement_kind.as_str(),s.status,s.started_at_ms,s.first_output_at_ms,s.last_output_at_ms,s.completed_at_ms,s.input_tokens,s.cached_input_tokens,s.reasoning_tokens,s.output_tokens,s.ttft_ms,s.observed_output_tps,s.end_to_end_output_tps,Utc::now().to_rfc3339()])?;conn.execute("DELETE FROM model_performance_samples WHERE provider=?1 AND model_id=?2 AND id NOT IN(SELECT id FROM model_performance_samples WHERE provider=?1 AND model_id=?2 ORDER BY completed_at_ms DESC,id DESC LIMIT 10000)",params![s.provider,s.model_id])?;Ok(())}
#[derive(Default)]struct Aggregate{tps:Vec<f64>,ttft:Vec<f64>,last:i64}
fn pct(v:&mut[f64],q:f64)->Option<f64>{if v.is_empty(){return None}v.sort_by(f64::total_cmp);v.get(((v.len()-1)as f64*q).round()as usize).copied()}
fn summaries(conn:&Connection)->Result<Vec<ModelPerformanceSummary>>{let mut stmt=conn.prepare("SELECT provider,model_id,measurement_kind,completed_at_ms,ttft_ms,observed_output_tps,end_to_end_output_tps FROM model_performance_samples WHERE status='completed'AND output_tokens IS NOT NULL AND output_tokens>0 ORDER BY completed_at_ms")?;let rows=stmt.query_map([],|r|Ok((r.get::<_,String>(0)?,r.get::<_,String>(1)?,r.get::<_,String>(2)?,r.get::<_,i64>(3)?,r.get::<_,Option<f64>>(4)?,r.get::<_,Option<f64>>(5)?,r.get::<_,Option<f64>>(6)?)))?;let mut groups:BTreeMap<(String,String,MeasurementKind),Aggregate>=BTreeMap::new();for row in rows{let(p,m,k,c,t,o,e)=row?;let a=groups.entry((p,m,MeasurementKind::parse(&k))).or_default();a.last=a.last.max(c);if let Some(v)=finite(t){a.ttft.push(v)}if let Some(v)=finite(o.or(e)){a.tps.push(v)}}Ok(groups.into_iter().filter_map(|((provider,model_id,measurement_kind),mut a)|{if a.tps.is_empty(){return None}let mut p95=a.tps.clone();let count=a.tps.len();Some(ModelPerformanceSummary{provider,model_id,measurement_kind,sample_count:count,tps_p50:pct(&mut a.tps,0.5),tps_p95:pct(&mut p95,0.95),ttft_p50_ms:pct(&mut a.ttft,0.5),last_observed_at:chrono::DateTime::<Utc>::from_timestamp_millis(a.last).unwrap_or_default().to_rfc3339()})}).collect())}

#[cfg(test)]mod tests{use super::*;#[test]fn rejects_thread_totals(){assert!(extract_usage(&serde_json::json!({"tokenUsage":{"totalUsage":{"outputTokens":99}}})).is_none());let u=extract_usage(&serde_json::json!({"tokenUsage":{"lastUsage":{"outputTokens":4}}})).unwrap();assert_eq!(u.output,Some(4));}}
