#!/usr/bin/env python3
"""Generate direct, typed calls from the authoritative Specta registration.

No business logic is copied. Rust infers each deserialized argument from the
actual handler signature. This generator fails closed on unfamiliar injections.
"""
import argparse
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
RUST = ROOT / 'apps/synth_desktop/src-tauri/src'
OUT = RUST / 'contract/desktop_dispatch.rs'


def split_arguments(text):
    depth = 0
    start = 0
    values = []
    for i, char in enumerate(text):
        if char in '<([{': depth += 1
        elif char in '>)]}': depth -= 1
        elif char == ',' and depth == 0:
            values.append(text[start:i].strip())
            start = i + 1
    values.append(text[start:].strip())
    return [v for v in values if v]


def generate():
    registry = (RUST / 'contract/specta.rs').read_text()
    entries = registry.split('.commands(collect_commands![')[1].split('])')[0]
    entries = [v.strip() for v in entries.split(',') if v.strip()]
    functions = {}
    for file in RUST.rglob('*.rs'):
        if 'third_party' in file.parts or file == OUT: continue
        text = file.read_text()
        pattern = r'#\[tauri::command[^\]]*\]\s*(?:#\[[\s\S]*?\]\s*)*(?:pub(?:\([^)]*\))?\s+)?(async\s+)?fn\s+(\w+)(?:<[^>]+>)?\s*\('
        for match in re.finditer(pattern, text):
            pos, depth = match.end(), 1
            end = pos
            while depth:
                if text[end] == '(': depth += 1
                if text[end] == ')': depth -= 1
                end += 1
            ret = text[end:text.index('{', end)].strip()
            functions.setdefault(match[2], []).append((file, bool(match[1]), text[pos:end-1], ret))
    lines = ['// @generated by scripts/generate-workshop-dispatch.py; do not edit.',
             'use anyhow::Context;', 'use serde_json::{json, Value};', 'use tauri::Manager;',
             'pub const NAMES: &[&str] = &[']
    for entry in entries: lines.append(f'    "{entry.split("::")[-1]}",')
    lines += ['];', '', "type Reply<'a> = std::pin::Pin<Box<dyn std::future::Future<Output = anyhow::Result<Value>> + Send + 'a>>;",
              "pub fn invoke<'a>(app: &'a tauri::AppHandle, name: &str, args: Value) -> Reply<'a> {", '    match name {']
    bodies = []
    for index, entry in enumerate(entries):
        name = entry.split('::')[-1]
        candidates = functions.get(name, [])
        if len(candidates) != 1: raise ValueError(f'{entry}: expected one command definition, got {len(candidates)}')
        file, asynchronous, signature, returns = candidates[0]
        arguments, names, declarations = [], [], []
        for arg in split_arguments(signature):
            parameter, ty = arg.split(':', 1)
            parameter, ty = parameter.strip(), ty.strip()
            if re.search(r'\bState\s*<', ty):
                arguments.append('app.try_state().context("runtime service is unavailable")?')
            elif re.search(r'\bAppHandle\b', ty): arguments.append('app.clone()')
            elif re.search(r'\bWebviewWindow\b', ty): arguments.append('app.get_webview_window("main").context("desktop_required: attach the desktop first")?')
            elif re.search(r'\bWindow\b', ty): arguments.append('app.get_window("main").context("desktop_required: attach the desktop first")?')
            else:
                if 'tauri::' in ty: raise ValueError(f'{entry}: unsupported host injection {ty}')
                wire = re.sub(r'_([a-z])', lambda m: m[1].upper(), parameter)
                names.append(wire)
                local = f'arg_{len(declarations)}'
                if ty == '&str':
                    declarations.append(f'let {local}: String = serde_json::from_value(args.get("{wire}").cloned().unwrap_or(Value::Null)).context("invalid {wire}")?;')
                    arguments.append(f'&{local}')
                else:
                    arguments.append(f'serde_json::from_value(args.get("{wire}").cloned().unwrap_or(Value::Null)).context("invalid {wire}")?')
        target = entry if entry.startswith('crate::') else f'crate::contract::specta::{entry}'
        call = f'{target}({", ".join(arguments)})' + ('.await' if asynchronous else '')
        if re.search(r'\b(?:Result|AppResult)\s*<', returns): call += '.map_err(|error| anyhow::anyhow!(format!("{error:?}")))?'
        lines.append(f'        "{name}" => operation_{index}(app, args),')
        bodies += [f"fn operation_{index}(app: &tauri::AppHandle, args: Value) -> Reply<'_> {{",
                  '    Box::pin(async move {', '            anyhow::ensure!(args.is_object(), "operation arguments must be an object");',
                  f'            // Handler: {file.relative_to(ROOT)}',
                  f'            let allowed: &[&str] = &{names!r};'.replace("'", '"'),
                  '            anyhow::ensure!(args.as_object().unwrap().keys().all(|key| allowed.contains(&key.as_str())), "unknown operation argument");']
        bodies += [f'            {v}' for v in declarations]
        bodies += [f'            let result = {call};', '            Ok(json!({"result": result}))', '    })', '}', '']
    lines += ['        _ => Box::pin(async { anyhow::bail!("unknown desktop operation") }),', '    }', '}', ''] + bodies
    return '\n'.join(lines)


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    generated = generate()
    if args.check:
        if not OUT.exists() or OUT.read_text() != generated: raise SystemExit('Desktop operation dispatch is stale; regenerate and review it')
    else: OUT.write_text(generated)
    print('Desktop operation dispatch verified' if args.check else 'Desktop operation dispatch generated')
