/**
 * Boundary channel + command name constants (Wave 2 interim).
 * Keep in sync with `src-tauri/src/contract/{events,commands}.rs`.
 * Specta seed bindings: `src/renderer/src/generated/protocol.ts` (grow via
 * `contract::specta::collect_commands!`); hand `COMMANDS` remains until cutover.
 * Drift: `scripts/check-desktop-contract-drift.sh` (via conform-desktop.sh).
 */

export const EVENT_CHANNELS = {
	/** Single origin-tagged session/runtime stream (Provider | Desktop). */
	RUNTIME: "runtime:event",
	/**
	 * @deprecated Producers no longer emit here. Compat listen only — remove
	 * once no leftover emitters remain.
	 */
	CODEX: "codex:event",
	VISUAL_SHOW: "visual:show",
	TERMINAL: "terminal:event",
	LAGUNA_STATUS: "laguna:status",
	LAGUNA_DOWNLOAD: "laguna:download",
	LAGUNA_INFERENCE: "laguna:inference",
	WHISPER_RUNTIME: "whisper:runtime",
	WHISPER_DOWNLOAD: "whisper:download",
	OPTIMIZER_STATUS: "optimizer:status"
} as const;

export type EventChannelName = (typeof EVENT_CHANNELS)[keyof typeof EVENT_CHANNELS];

/** Matches Rust `contract::events::EventOrigin`. */
export const EVENT_ORIGINS = {
	PROVIDER: "provider",
	DESKTOP: "desktop"
} as const;

export type EventOrigin = (typeof EVENT_ORIGINS)[keyof typeof EVENT_ORIGINS];

export const COMMANDS = {
	CORE_DIAGNOSTICS: "core_diagnostics",
	CORE_EVENTS_AFTER: "core_events_after",
	CORE_SESSION_EVENTS_AFTER: "core_session_events_after",
	INTERN_SESSIONS_LIST: "intern_sessions_list",
	INTERN_SESSION_CREATE: "intern_session_create",
	INTERN_SESSION_SEND: "intern_session_send",
	INTERN_SESSION_CONTROL: "intern_session_control",
	INTERN_SESSION_EVENTS_AFTER: "intern_session_events_after",
	CODEX_DEFAULT_WORKSPACE: "codex_default_workspace",
	CODEX_SESSIONS_LIST: "codex_sessions_list",
	CODEX_SESSION_START: "codex_session_start",
	CODEX_TURN_START: "codex_turn_start",
	CODEX_TURN_SEND: "codex_turn_send",
	CODEX_TURN_INTERRUPT: "codex_turn_interrupt",
	CODEX_THREAD_COMPACT: "codex_thread_compact",
	CODEX_THREAD_READ: "codex_thread_read",
	CODEX_THREAD_ITEMS_LIST: "codex_thread_items_list",
	CODEX_TURN_STEER: "codex_turn_steer",
	CODEX_APPROVAL_RESOLVE: "codex_approval_resolve",
	CODEX_SESSION_CLOSE: "codex_session_close",
	ACCOUNT_BEGIN_SIGN_IN: "account_begin_sign_in",
	ACCOUNT_POLL_SIGN_IN: "account_poll_sign_in",
	ACCOUNT_CANCEL_SIGN_IN: "account_cancel_sign_in",
	ACCOUNT_SIGN_OUT: "account_sign_out",
	ACCOUNT_GET_SUMMARY: "account_get_summary",
	ACCOUNT_REFRESH: "account_refresh",
	ACCOUNT_OPEN_BILLING: "account_open_billing",
	CODEX_OAUTH_BEGIN: "codex_oauth_begin",
	CODEX_OAUTH_COMPLETE_MANUAL: "codex_oauth_complete_manual",
	CODEX_OAUTH_STATUS: "codex_oauth_status",
	CODEX_OAUTH_ENSURE_READY: "codex_oauth_ensure_ready",
	CODEX_OAUTH_DISCONNECT: "codex_oauth_disconnect",
	CODEX_OAUTH_CANCEL: "codex_oauth_cancel",
	SYNTH_CONFIG_GET: "synth_config_get",
	SYNTH_CONFIG_UPDATE: "synth_config_update",
	MODEL_MULTI_AGENT_LIST: "model_multi_agent_list",
	MODEL_MULTI_AGENT_UPDATE: "model_multi_agent_update",
	WORKSPACE_ACCESS_GET: "workspace_access_get",
	WORKSPACE_ACCESS_UPDATE: "workspace_access_update",
	DESKTOP_PERMISSIONS_GET: "desktop_permissions_get",
	DESKTOP_PERMISSIONS_UPDATE: "desktop_permissions_update",
	WORKSPACE_SCOPE_GET: "workspace_scope_get",
	WORKSPACE_SCOPE_CHOOSE_AND_ATTACH: "workspace_scope_choose_and_attach",
	WORKSPACE_SCOPE_RECENT_FOLDERS: "workspace_scope_recent_folders",
	WORKSPACE_SCOPE_ATTACH_RECENT: "workspace_scope_attach_recent",
	WORKSPACE_SCOPE_REMOVE_ATTACHMENT: "workspace_scope_remove_attachment",
	WORKSPACE_SCOPE_GRANTS_LIST: "workspace_scope_grants_list",
	WORKSPACE_SCOPE_APPROVE_REQUEST: "workspace_scope_approve_request",
	WORKSPACE_SCOPE_DENY_REQUEST: "workspace_scope_deny_request",
	LAGUNA_GET_STATUS: "laguna_get_status",
	LAGUNA_RELOAD: "laguna_reload",
	LAGUNA_MODELS_LIST: "laguna_models_list",
	LAGUNA_MODEL_DOWNLOAD: "laguna_model_download",
	LAGUNA_MODEL_UNLOAD: "laguna_model_unload",
	LAGUNA_INFERENCE_STREAM_START: "laguna_inference_stream_start",
	LAGUNA_INFERENCE_STREAM_STOP: "laguna_inference_stream_stop",
	LAGUNA_INFERENCE_SNAPSHOT: "laguna_inference_snapshot",
	LAGUNA_SETTINGS_SNAPSHOT: "laguna_settings_snapshot",
	LAGUNA_SETTINGS_UPDATE: "laguna_settings_update",
	WHISPER_RUNTIME_STATUS: "whisper_runtime_status",
	WHISPER_RUNTIME_WARM: "whisper_runtime_warm",
	WHISPER_MODELS_LIST: "whisper_models_list",
	WHISPER_MODEL_DOWNLOAD: "whisper_model_download",
	WHISPER_MODELS_SET_SELECTED: "whisper_models_set_selected",
	WHISPER_MODELS_CLEAR: "whisper_models_clear",
	WHISPER_TRANSCRIBE: "whisper_transcribe",
	WHISPER_TRANSCRIBE_BASE64: "whisper_transcribe_base64",
	TERMINAL_CREATE: "terminal_create",
	TERMINAL_LIST: "terminal_list",
	TERMINAL_SNAPSHOT: "terminal_snapshot",
	TERMINAL_WRITE: "terminal_write",
	TERMINAL_RESIZE: "terminal_resize",
	TERMINAL_CLOSE: "terminal_close",
	DATA_CONTAINERS_LIST: "data_containers_list",
	DATA_CONTAINERS_GET: "data_containers_get",
	DATA_CONTAINERS_REGISTER: "data_containers_register",
	DATA_CONTAINERS_PROBE: "data_containers_probe",
	DATA_TRACES_LIST: "data_traces_list",
	DATA_TRACES_GET: "data_traces_get",
	DATA_TRACES_INGEST: "data_traces_ingest",
	DATA_TRACE_PROJECTION_RESOLVE: "data_trace_projection_resolve",
	DATA_USAGE_LIST: "data_usage_list",
	DATA_COUNTS: "data_counts",
	MODEL_PERFORMANCE_SUMMARY: "model_performance_summary",
	MODEL_PERFORMANCE_GET: "model_performance_get",
	USAGE_SUMMARY: "usage_summary",
	TARIFF_CATALOG: "tariff_catalog",
	UPDATE_STATUS: "update_status",
	UPDATE_OPEN_DOWNLOAD: "update_open_download",
	SKILLS_LIST: "skills_list",
	CONTEXT_SNAPSHOT: "context_snapshot",
	CONTEXT_WORKSPACE_AGENTS_UPDATE: "context_workspace_agents_update",
	CONTEXT_SKILL_UPDATE: "context_skill_update",
	CONTEXT_MCP_GROUP_UPDATE: "context_mcp_group_update",
	CONTEXT_COOKBOOKS_INSTALL: "context_cookbooks_install",
	CONTEXT_COOKBOOKS_CANCEL: "context_cookbooks_cancel",
	CONTEXT_COOKBOOKS_SET_ENABLED: "context_cookbooks_set_enabled",
	CONTEXT_COOKBOOKS_UNINSTALL: "context_cookbooks_uninstall",
	VISUALS_TEMPLATES_LIST: "visuals_templates_list",
	VISUALS_TEMPLATES_GET: "visuals_templates_get",
	VISUALS_LIST: "visuals_list",
	VISUALS_GET: "visuals_get",
	VISUALS_REVISIONS: "visuals_revisions",
	VISUALS_ANNOTATIONS_LIST: "visuals_annotations_list",
	VISUALS_ANNOTATION_CREATE: "visuals_annotation_create",
	VISUALS_SEALS_LIST: "visuals_seals_list",
	VISUALS_SEAL: "visuals_seal",
	VISUALS_SEAL_GET: "visuals_seal_get",
	VISUALS_UPLOAD_STATUS: "visuals_upload_status",
	VISUALS_SHARE_SEAL: "visuals_share_seal",
	VISUALS_OPEN_SHARED: "visuals_open_shared",
	VISUALS_CREATE: "visuals_create",
	VISUALS_UPDATE: "visuals_update",
	VISUALS_SAVE: "visuals_save",
	VISUALS_FORK: "visuals_fork",
	VISUALS_ARCHIVE: "visuals_archive",
	VISUALS_SHOW: "visuals_show",
	VISUALS_CONTENT: "visuals_content",
	VISUALS_RENDITIONS: "visuals_renditions",
	VISUALS_RENDITION: "visuals_rendition",
	VISUALS_RENDER: "visuals_render",
	REPORTS_LIST: "reports_list",
	REPORTS_GET: "reports_get",
	REPORTS_REVISION_GET: "reports_revision_get",
	REPORTS_CREATE: "reports_create",
	REPORTS_UPDATE: "reports_update",
	REPORTS_ARCHIVE: "reports_archive",
	REPORTS_RESTORE: "reports_restore",
	REPORTS_VISIBILITY_REQUESTS: "reports_visibility_requests",
	REPORTS_VISIBILITY_REQUEST: "reports_visibility_request",
	REPORTS_VISIBILITY_DECIDE: "reports_visibility_decide",
	REPORTS_SEAL: "reports_seal",
	REPORTS_SEALS_LIST: "reports_seals_list",
	REPORTS_SEAL_GET: "reports_seal_get",
	REPORTS_SEALS_COMPARE: "reports_seals_compare",
	REPORTS_EXPERIMENTS_LIST: "reports_experiments_list",
	REPORTS_EXPERIMENT_UPSERT: "reports_experiment_upsert",
	REPORTS_LOG_LIST: "reports_log_list",
	REPORTS_LOG_APPEND: "reports_log_append",
	REPORTS_UPLOAD_STATUS: "reports_upload_status",
	REPORTS_SHARE: "reports_share",
	REPORTS_PROMOTE: "reports_promote",
	REPORTS_OPEN_SHARED: "reports_open_shared",
	REPORTS_COMMENTS_LIST: "reports_comments_list",
	REPORTS_COMMENT_CREATE: "reports_comment_create",
	OPTIMIZERS_ALGORITHMS_LIST: "optimizers_algorithms_list",
	OPTIMIZERS_RECIPES_LIST: "optimizers_recipes_list",
	OPTIMIZERS_RECIPE_START: "optimizers_recipe_start",
	OPTIMIZERS_LIST: "optimizers_list",
	OPTIMIZERS_GET: "optimizers_get",
	OPTIMIZERS_CREATE: "optimizers_create",
	OPTIMIZERS_REFRESH: "optimizers_refresh",
	OPTIMIZERS_EVENTS_AFTER: "optimizers_events_after",
	OPTIMIZERS_GET_STATE: "optimizers_get_state",
	OPTIMIZERS_GET_STATE_BATCH: "optimizers_get_state_batch",
	OPTIMIZERS_CANCEL: "optimizers_cancel",
	OPTIMIZERS_PAUSE: "optimizers_pause",
	OPTIMIZERS_RESUME: "optimizers_resume",
	OPTIMIZERS_OPEN_VISUAL: "optimizers_open_visual",
	OPTIMIZERS_IMPORT_LOCAL: "optimizers_import_local",
	OPTIMIZERS_RECONCILE_CLOUD: "optimizers_reconcile_cloud",
	OPTIMIZERS_LIST_CLOUD: "optimizers_list_cloud",
	PLUGINS_STATUS: "plugins_status",
	PLUGINS_LIST: "plugins_list",
	PLUGINS_MANAGE: "plugins_manage",
	PLUGINS_SET_RELEASE_CHANNEL: "plugins_set_release_channel",
	VISUAL_SUBSCRIPTION_READY: "visual_subscription_ready",
	OPTIMIZER_SIDECAR_STATUS: "optimizer_sidecar_status",
	OPTIMIZER_SIDECAR_INSTALL: "optimizer_sidecar_install",
	OPTIMIZER_SIDECAR_START: "optimizer_sidecar_start",
	OPTIMIZER_SIDECAR_STOP: "optimizer_sidecar_stop",
	OPTIMIZER_SIDECAR_VERSION: "optimizer_sidecar_version",
	OPTIMIZER_SIDECAR_UNINSTALL: "optimizer_sidecar_uninstall",
	DESKTOP_IMAGE_PREVIEW: "desktop_image_preview",
	DESKTOP_INSTANCE_DIAGNOSTICS: "desktop_instance_diagnostics",
	WORKSPACE_CHOOSE_DIRECTORY: "workspace_choose_directory",
	LAGUNA_MODELS_SET_DIRECTORY: "laguna_models_set_directory",
	LAGUNA_MODELS_CLEAR_DIRECTORY: "laguna_models_clear_directory",
	LAGUNA_MODEL_DELETE: "laguna_model_delete",
	MIGRATION_SCAN: "migration_scan",
	MIGRATION_PREPARE: "migration_prepare",
	MIGRATION_APPLY: "migration_apply",
	MIGRATION_CANCEL: "migration_cancel"
} as const;

export type CommandName = (typeof COMMANDS)[keyof typeof COMMANDS];
